<?php
/*****************************************************************************
 *   Copyright (C) 2006-2008, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2009-03-10 19:17:16                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoBind2Item extends IdentifiableObject
	{
		protected $item = null;
		protected $itemId = null;
		protected $bindItem = null;
		protected $bindItemId = null;
		
		/**
		 * @return Item
		**/
		public function getItem()
		{
			if (!$this->item) {
				$this->item = Item::dao()->getById($this->itemId);
			}
			
			return $this->item;
		}
		
		public function getItemId()
		{
			return $this->itemId;
		}
		
		/**
		 * @return Item
		**/
		public function setItem(Item $item)
		{
			$this->item = $item;
			$this->itemId = $item->getId();
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function setItemId($id)
		{
			$this->item = null;
			$this->itemId = $id;
			
			return $this;
		}
		
		/**
		 * @return Bind2Item
		**/
		public function dropItem()
		{
			$this->item = null;
			$this->itemId = null;
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function getBindItem()
		{
			if (!$this->bindItem) {
				$this->bindItem = Item::dao()->getById($this->bindItemId);
			}
			
			return $this->bindItem;
		}
		
		public function getBindItemId()
		{
			return $this->bindItemId;
		}
		
		/**
		 * @return Item
		**/
		public function setBindItem(Item $bindItem)
		{
			$this->bindItem = $bindItem;
			$this->bindItemId = $bindItem->getId();
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function setBindItemId($id)
		{
			$this->bindItem = null;
			$this->bindItemId = $id;
			
			return $this;
		}
		
		/**
		 * @return Bind2Item
		**/
		public function dropBindItem()
		{
			$this->bindItem = null;
			$this->bindItemId = null;
			
			return $this;
		}
	}
?>