<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2011-08-14 16:48:23                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoItem extends IdentifiableObject
	{
		protected $itemName = null;
		protected $itemDescription = null;
		protected $itemOrder = null;
		protected $classType = null;
		protected $parentClass = null;
		protected $mainPropertyDescription = null;
		protected $mainPropertyParameters = null;
		protected $isFolder = false;
		protected $pathPrefix = null;
		protected $isUpdatePath = false;
		protected $orderField = null;
		protected $orderDirection = null;
		protected $perPage = 0;
		protected $isSearch = false;
		
		public function getItemName()
		{
			return $this->itemName;
		}
		
		/**
		 * @return Item
		**/
		public function setItemName($itemName)
		{
			$this->itemName = $itemName;
			
			return $this;
		}
		
		public function getItemDescription()
		{
			return $this->itemDescription;
		}
		
		/**
		 * @return Item
		**/
		public function setItemDescription($itemDescription)
		{
			$this->itemDescription = $itemDescription;
			
			return $this;
		}
		
		public function getItemOrder()
		{
			return $this->itemOrder;
		}
		
		/**
		 * @return Item
		**/
		public function setItemOrder($itemOrder)
		{
			$this->itemOrder = $itemOrder;
			
			return $this;
		}
		
		public function getClassType()
		{
			return $this->classType;
		}
		
		/**
		 * @return Item
		**/
		public function setClassType($classType)
		{
			$this->classType = $classType;
			
			return $this;
		}
		
		public function getParentClass()
		{
			return $this->parentClass;
		}
		
		/**
		 * @return Item
		**/
		public function setParentClass($parentClass)
		{
			$this->parentClass = $parentClass;
			
			return $this;
		}
		
		public function getMainPropertyDescription()
		{
			return $this->mainPropertyDescription;
		}
		
		/**
		 * @return Item
		**/
		public function setMainPropertyDescription($mainPropertyDescription)
		{
			$this->mainPropertyDescription = $mainPropertyDescription;
			
			return $this;
		}
		
		public function getMainPropertyParameters()
		{
			return $this->mainPropertyParameters;
		}
		
		/**
		 * @return Item
		**/
		public function setMainPropertyParameters($mainPropertyParameters)
		{
			$this->mainPropertyParameters = $mainPropertyParameters;
			
			return $this;
		}
		
		public function getIsFolder()
		{
			return $this->isFolder;
		}
		
		public function isIsFolder()
		{
			return $this->isFolder;
		}
		
		/**
		 * @return Item
		**/
		public function setIsFolder($isFolder = false)
		{
			$this->isFolder = ($isFolder === true);
			
			return $this;
		}
		
		public function getPathPrefix()
		{
			return $this->pathPrefix;
		}
		
		/**
		 * @return Item
		**/
		public function setPathPrefix($pathPrefix)
		{
			$this->pathPrefix = $pathPrefix;
			
			return $this;
		}
		
		public function getIsUpdatePath()
		{
			return $this->isUpdatePath;
		}
		
		public function isIsUpdatePath()
		{
			return $this->isUpdatePath;
		}
		
		/**
		 * @return Item
		**/
		public function setIsUpdatePath($isUpdatePath = false)
		{
			$this->isUpdatePath = ($isUpdatePath === true);
			
			return $this;
		}
		
		public function getOrderField()
		{
			return $this->orderField;
		}
		
		/**
		 * @return Item
		**/
		public function setOrderField($orderField)
		{
			$this->orderField = $orderField;
			
			return $this;
		}
		
		public function getOrderDirection()
		{
			return $this->orderDirection;
		}
		
		public function isOrderDirection()
		{
			return $this->orderDirection;
		}
		
		/**
		 * @return Item
		**/
		public function setOrderDirection($orderDirection = false)
		{
			$this->orderDirection = ($orderDirection === true);
			
			return $this;
		}
		
		public function getPerPage()
		{
			return $this->perPage;
		}
		
		/**
		 * @return Item
		**/
		public function setPerPage($perPage)
		{
			$this->perPage = $perPage;
			
			return $this;
		}
		
		public function getIsSearch()
		{
			return $this->isSearch;
		}
		
		public function isIsSearch()
		{
			return $this->isSearch;
		}
		
		/**
		 * @return Item
		**/
		public function setIsSearch($isSearch = false)
		{
			$this->isSearch = ($isSearch === true);
			
			return $this;
		}
	}
?>