<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-07-24 14:51:10                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoElement extends IdentifiableObject
	{
		protected $elementName = null;
		protected $elementOrder = null;
		protected $status = null;
		protected $elementPath = null;
		protected $group = null;
		protected $groupId = null;
		protected $user = null;
		protected $userId = null;

		public function getElementName()
		{
			return $this->elementName;
		}

		/**
		 * @return Element
		**/
		public function setElementName($elementName)
		{
			$this->elementName = $elementName;

			return $this;
		}

		public function getElementOrder()
		{
			return $this->elementOrder;
		}

		/**
		 * @return Element
		**/
		public function setElementOrder($elementOrder)
		{
			$this->elementOrder = $elementOrder;

			return $this;
		}

		public function getStatus()
		{
			return $this->status;
		}

		/**
		 * @return Element
		**/
		public function setStatus($status)
		{
			$this->status = $status;

			return $this;
		}

		public function getElementPath()
		{
			return $this->elementPath;
		}

		/**
		 * @return Element
		**/
		public function setElementPath($elementPath)
		{
			$this->elementPath = $elementPath;

			return $this;
		}

		/**
		 * @return Group
		**/
		public function getGroup()
		{
			if (!$this->group && $this->groupId) {
				$this->group = Group::dao()->getById($this->groupId);
			}

			return $this->group;
		}

		public function getGroupId()
		{
			return $this->groupId;
		}

		/**
		 * @return Element
		**/
		public function setGroup(Group $group)
		{
			$this->group = $group;
			$this->groupId = $group->getId();

			return $this;
		}

		/**
		 * @return Element
		**/
		public function setGroupId($id)
		{
			$this->group = null;
			$this->groupId = $id;

			return $this;
		}

		/**
		 * @return Element
		**/
		public function dropGroup()
		{
			$this->group = null;
			$this->groupId = null;

			return $this;
		}

		/**
		 * @return User
		**/
		public function getUser()
		{
			if (!$this->user && $this->userId) {
				$this->user = User::dao()->getById($this->userId);
			}

			return $this->user;
		}

		public function getUserId()
		{
			return $this->userId;
		}

		/**
		 * @return Element
		**/
		public function setUser(User $user)
		{
			$this->user = $user;
			$this->userId = $user->getId();

			return $this;
		}

		/**
		 * @return Element
		**/
		public function setUserId($id)
		{
			$this->user = null;
			$this->userId = $id;

			return $this;
		}

		/**
		 * @return Element
		**/
		public function dropUser()
		{
			$this->user = null;
			$this->userId = null;

			return $this;
		}
	}
?>