<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2014-10-19 11:05:04                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoUser extends IdentifiableObject
	{
		protected $group = null;
		protected $groupId = null;
		protected $userName = null;
		protected $userPassword = null;
		protected $userDescription = null;
		protected $userEmail = null;
		protected $userParameters = null;
		protected $registrationDate = null;
		protected $loginDate = null;
		protected $banned = false;
		
		/**
		 * @return Group
		**/
		public function getGroup()
		{
			if (!$this->group && $this->groupId) {
				$this->group = Group::dao()->getById($this->groupId);
			}
			
			return $this->group;
		}
		
		public function getGroupId()
		{
			return $this->groupId;
		}
		
		/**
		 * @return User
		**/
		public function setGroup(Group $group)
		{
			$this->group = $group;
			$this->groupId = $group->getId();
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function setGroupId($id)
		{
			$this->group = null;
			$this->groupId = $id;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropGroup()
		{
			$this->group = null;
			$this->groupId = null;
			
			return $this;
		}
		
		public function getUserName()
		{
			return $this->userName;
		}
		
		/**
		 * @return User
		**/
		public function setUserName($userName)
		{
			$this->userName = $userName;
			
			return $this;
		}
		
		public function getUserPassword()
		{
			return $this->userPassword;
		}
		
		/**
		 * @return User
		**/
		public function setUserPassword($userPassword)
		{
			$this->userPassword = $userPassword;
			
			return $this;
		}
		
		public function getUserDescription()
		{
			return $this->userDescription;
		}
		
		/**
		 * @return User
		**/
		public function setUserDescription($userDescription)
		{
			$this->userDescription = $userDescription;
			
			return $this;
		}
		
		public function getUserEmail()
		{
			return $this->userEmail;
		}
		
		/**
		 * @return User
		**/
		public function setUserEmail($userEmail)
		{
			$this->userEmail = $userEmail;
			
			return $this;
		}
		
		public function getUserParameters()
		{
			return $this->userParameters;
		}
		
		/**
		 * @return User
		**/
		public function setUserParameters($userParameters)
		{
			$this->userParameters = $userParameters;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getRegistrationDate()
		{
			return $this->registrationDate;
		}
		
		/**
		 * @return User
		**/
		public function setRegistrationDate(Timestamp $registrationDate)
		{
			$this->registrationDate = $registrationDate;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropRegistrationDate()
		{
			$this->registrationDate = null;
			
			return $this;
		}
		
		/**
		 * @return Timestamp
		**/
		public function getLoginDate()
		{
			return $this->loginDate;
		}
		
		/**
		 * @return User
		**/
		public function setLoginDate(Timestamp $loginDate)
		{
			$this->loginDate = $loginDate;
			
			return $this;
		}
		
		/**
		 * @return User
		**/
		public function dropLoginDate()
		{
			$this->loginDate = null;
			
			return $this;
		}
		
		public function getBanned()
		{
			return $this->banned;
		}
		
		public function isBanned()
		{
			return $this->banned;
		}
		
		/**
		 * @return User
		**/
		public function setBanned($banned = false)
		{
			$this->banned = ($banned === true);
			
			return $this;
		}
	}
?>