<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2010-01-21 00:32:10                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoItemPermission extends IdentifiableObject
	{
		protected $group = null;
		protected $groupId = null;
		protected $item = null;
		protected $itemId = null;
		protected $ownerPermission = 0;
		protected $groupPermission = 0;
		protected $worldPermission = 0;
		protected $isSearch = false;
		
		/**
		 * @return Group
		**/
		public function getGroup()
		{
			if (!$this->group && $this->groupId) {
				$this->group = Group::dao()->getById($this->groupId);
			}
			
			return $this->group;
		}
		
		public function getGroupId()
		{
			return $this->groupId;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setGroup(Group $group)
		{
			$this->group = $group;
			$this->groupId = $group->getId();
			
			return $this;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setGroupId($id)
		{
			$this->group = null;
			$this->groupId = $id;
			
			return $this;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function dropGroup()
		{
			$this->group = null;
			$this->groupId = null;
			
			return $this;
		}
		
		/**
		 * @return Item
		**/
		public function getItem()
		{
			if (!$this->item && $this->itemId) {
				$this->item = Item::dao()->getById($this->itemId);
			}
			
			return $this->item;
		}
		
		public function getItemId()
		{
			return $this->itemId;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setItem(Item $item)
		{
			$this->item = $item;
			$this->itemId = $item->getId();
			
			return $this;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setItemId($id)
		{
			$this->item = null;
			$this->itemId = $id;
			
			return $this;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function dropItem()
		{
			$this->item = null;
			$this->itemId = null;
			
			return $this;
		}
		
		public function getOwnerPermission()
		{
			return $this->ownerPermission;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setOwnerPermission($ownerPermission)
		{
			$this->ownerPermission = $ownerPermission;
			
			return $this;
		}
		
		public function getGroupPermission()
		{
			return $this->groupPermission;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setGroupPermission($groupPermission)
		{
			$this->groupPermission = $groupPermission;
			
			return $this;
		}
		
		public function getWorldPermission()
		{
			return $this->worldPermission;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setWorldPermission($worldPermission)
		{
			$this->worldPermission = $worldPermission;
			
			return $this;
		}
		
		public function getIsSearch()
		{
			return $this->isSearch;
		}
		
		public function isIsSearch()
		{
			return $this->isSearch;
		}
		
		/**
		 * @return ItemPermission
		**/
		public function setIsSearch($isSearch = false)
		{
			$this->isSearch = ($isSearch === true);
			
			return $this;
		}
	}
?>