<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2009-03-04 22:45:02                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoBind2Item extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'identifier', 'Bind2Item', 4, true, true, false, null, null),
				'item' => LightMetaProperty::fill(new LightMetaProperty(), 'item', 'item_id', 'identifier', 'Item', 4, true, false, false, 1, 3),
				'bindItem' => LightMetaProperty::fill(new LightMetaProperty(), 'bindItem', 'bind_item_id', 'identifier', 'Item', 4, true, false, false, 1, 3)
			);
		}
	}
?>