<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-10-14 18:51:38                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoUserAction extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'UserAction', 4, true, true, false, null, null),
				'user' => LightMetaProperty::fill(new LightMetaProperty(), 'user', 'user_id', 'identifier', 'User', 4, true, false, false, 1, 3),
				'actionTypeId' => LightMetaProperty::fill(new LightMetaProperty(), 'actionTypeId', 'action_type_id', 'integer', null, 4, true, true, false, null, null),
				'comments' => LightMetaProperty::fill(new LightMetaProperty(), 'comments', null, 'string', null, null, false, true, false, null, null),
				'url' => LightMetaProperty::fill(new LightMetaProperty(), 'url', null, 'string', null, 255, true, true, false, null, null),
				'date' => LightMetaProperty::fill(new LightMetaProperty(), 'date', null, 'timestamp', 'Timestamp', null, true, true, false, null, null)
			);
		}
	}
?>