<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2011-08-14 16:48:23                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoItem extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'Item', 4, true, true, false, null, null),
				'itemName' => LightMetaProperty::fill(new LightMetaProperty(), 'itemName', 'item_name', 'string', null, 50, true, true, false, null, null),
				'itemDescription' => LightMetaProperty::fill(new LightMetaProperty(), 'itemDescription', 'item_description', 'string', null, 255, true, true, false, null, null),
				'itemOrder' => LightMetaProperty::fill(new LightMetaProperty(), 'itemOrder', 'item_order', 'integer', null, 4, false, true, false, null, null),
				'classType' => LightMetaProperty::fill(new LightMetaProperty(), 'classType', 'class_type', 'string', null, 50, false, true, false, null, null),
				'parentClass' => LightMetaProperty::fill(new LightMetaProperty(), 'parentClass', 'parent_class', 'string', null, 50, false, true, false, null, null),
				'mainPropertyDescription' => LightMetaProperty::fill(new LightMetaProperty(), 'mainPropertyDescription', 'main_property_description', 'string', null, 255, false, true, false, null, null),
				'mainPropertyParameters' => LightMetaProperty::fill(new LightMetaProperty(), 'mainPropertyParameters', 'main_property_parameters', 'string', null, null, false, true, false, null, null),
				'isFolder' => LightMetaProperty::fill(new LightMetaProperty(), 'isFolder', 'is_folder', 'boolean', null, null, true, true, false, null, null),
				'pathPrefix' => LightMetaProperty::fill(new LightMetaProperty(), 'pathPrefix', 'path_prefix', 'string', null, 50, false, true, false, null, null),
				'isUpdatePath' => LightMetaProperty::fill(new LightMetaProperty(), 'isUpdatePath', 'is_update_path', 'boolean', null, null, true, true, false, null, null),
				'orderField' => LightMetaProperty::fill(new LightMetaProperty(), 'orderField', 'order_field', 'string', null, 50, false, true, false, null, null),
				'orderDirection' => LightMetaProperty::fill(new LightMetaProperty(), 'orderDirection', 'order_direction', 'boolean', null, null, true, true, false, null, null),
				'perPage' => LightMetaProperty::fill(new LightMetaProperty(), 'perPage', 'per_page', 'integer', null, 4, false, true, false, null, null),
				'isSearch' => LightMetaProperty::fill(new LightMetaProperty(), 'isSearch', 'is_search', 'boolean', null, null, true, true, false, null, null)
			);
		}
	}
?>