<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2009-03-04 22:45:02                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoItem extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'identifier', 'Item', 4, true, true, false, null, null),
				'itemName' => LightMetaProperty::fill(new LightMetaProperty(), 'itemName', 'item_name', 'string', null, 50, true, true, false, null, null),
				'itemDescription' => LightMetaProperty::fill(new LightMetaProperty(), 'itemDescription', 'item_description', 'string', null, 255, true, true, false, null, null),
				'itemOrder' => LightMetaProperty::fill(new LightMetaProperty(), 'itemOrder', 'item_order', 'integer', null, 4, false, true, false, null, null),
				'classType' => LightMetaProperty::fill(new LightMetaProperty(), 'classType', 'class_type', 'string', null, 50, false, true, false, null, null),
				'parentClass' => LightMetaProperty::fill(new LightMetaProperty(), 'parentClass', 'parent_class', 'string', null, 50, false, true, false, null, null),
				'classSource' => LightMetaProperty::fill(new LightMetaProperty(), 'classSource', 'class_source', 'string', null, 50, false, true, false, null, null),
				'tableName' => LightMetaProperty::fill(new LightMetaProperty(), 'tableName', 'table_name', 'string', null, 255, false, true, false, null, null),
				'mainPropertyDescription' => LightMetaProperty::fill(new LightMetaProperty(), 'mainPropertyDescription', 'main_property_description', 'string', null, 255, false, true, false, null, null),
				'controllerName' => LightMetaProperty::fill(new LightMetaProperty(), 'controllerName', 'controller_name', 'string', null, 50, false, true, false, null, null),
				'pluginName' => LightMetaProperty::fill(new LightMetaProperty(), 'pluginName', 'plugin_name', 'string', null, 50, false, true, false, null, null),
				'filterName' => LightMetaProperty::fill(new LightMetaProperty(), 'filterName', 'filter_name', 'string', null, 50, false, true, false, null, null),
				'beforeInsert' => LightMetaProperty::fill(new LightMetaProperty(), 'beforeInsert', 'before_insert', 'string', null, 50, false, true, false, null, null),
				'afterInsert' => LightMetaProperty::fill(new LightMetaProperty(), 'afterInsert', 'after_insert', 'string', null, 50, false, true, false, null, null),
				'beforeUpdate' => LightMetaProperty::fill(new LightMetaProperty(), 'beforeUpdate', 'before_update', 'string', null, 50, false, true, false, null, null),
				'afterUpdate' => LightMetaProperty::fill(new LightMetaProperty(), 'afterUpdate', 'after_update', 'string', null, 50, false, true, false, null, null),
				'beforeDelete' => LightMetaProperty::fill(new LightMetaProperty(), 'beforeDelete', 'before_delete', 'string', null, 50, false, true, false, null, null),
				'afterDelete' => LightMetaProperty::fill(new LightMetaProperty(), 'afterDelete', 'after_delete', 'string', null, 50, false, true, false, null, null),
				'isFolder' => LightMetaProperty::fill(new LightMetaProperty(), 'isFolder', 'is_folder', 'boolean', null, null, false, true, false, null, null),
				'pathPrefix' => LightMetaProperty::fill(new LightMetaProperty(), 'pathPrefix', 'path_prefix', 'string', null, 50, false, true, false, null, null),
				'orderField' => LightMetaProperty::fill(new LightMetaProperty(), 'orderField', 'order_field', 'string', null, 50, false, true, false, null, null),
				'orderDirection' => LightMetaProperty::fill(new LightMetaProperty(), 'orderDirection', 'order_direction', 'boolean', null, null, false, true, false, null, null),
				'perPage' => LightMetaProperty::fill(new LightMetaProperty(), 'perPage', 'per_page', 'integer', null, 4, false, true, false, null, null)
			);
		}
	}
?>