<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-07-24 14:51:10                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoItemPermission extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'ItemPermission', 4, true, true, false, null, null),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'identifier', 'Group', 4, true, false, false, 1, 3),
				'item' => LightMetaProperty::fill(new LightMetaProperty(), 'item', 'item_id', 'identifier', 'Item', 4, true, false, false, 1, 3),
				'ownerPermission' => LightMetaProperty::fill(new LightMetaProperty(), 'ownerPermission', 'owner_permission', 'integer', null, 4, true, true, false, null, null),
				'groupPermission' => LightMetaProperty::fill(new LightMetaProperty(), 'groupPermission', 'group_permission', 'integer', null, 4, true, true, false, null, null),
				'worldPermission' => LightMetaProperty::fill(new LightMetaProperty(), 'worldPermission', 'world_permission', 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>