<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2009-03-04 22:45:02                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoUser extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'identifier', 'User', 4, true, true, false, null, null),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'identifier', 'Group', 4, true, false, false, 1, 3),
				'userName' => LightMetaProperty::fill(new LightMetaProperty(), 'userName', 'user_name', 'string', null, 50, true, true, false, null, null),
				'userPassword' => LightMetaProperty::fill(new LightMetaProperty(), 'userPassword', 'user_password', 'string', null, 255, true, true, false, null, null),
				'userDescription' => LightMetaProperty::fill(new LightMetaProperty(), 'userDescription', 'user_description', 'string', null, 255, true, true, false, null, null),
				'userEmail' => LightMetaProperty::fill(new LightMetaProperty(), 'userEmail', 'user_email', 'string', null, 255, false, true, false, null, null),
				'registrationDate' => LightMetaProperty::fill(new LightMetaProperty(), 'registrationDate', 'registration_date', 'timestamp', 'Timestamp', null, true, true, false, null, null),
				'loginDate' => LightMetaProperty::fill(new LightMetaProperty(), 'loginDate', 'login_date', 'timestamp', 'Timestamp', null, true, true, false, null, null)
			);
		}
	}
?>