<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-07-24 14:51:10                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoProtoElementPermission extends AbstractProtoClass
	{
		protected function makePropertyList()
		{
			return array(
				'id' => LightMetaProperty::fill(new LightMetaProperty(), 'id', null, 'integerIdentifier', 'ElementPermission', 4, true, true, false, null, null),
				'group' => LightMetaProperty::fill(new LightMetaProperty(), 'group', 'group_id', 'identifier', 'Group', 4, true, false, false, 1, 3),
				'elementId' => LightMetaProperty::fill(new LightMetaProperty(), 'elementId', 'element_id', 'string', null, 50, true, true, false, null, null),
				'permission' => LightMetaProperty::fill(new LightMetaProperty(), 'permission', null, 'integer', null, 4, true, true, false, null, null)
			);
		}
	}
?>