<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-03-31 16:27:56                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class Bind2ElementDAO extends AutoBind2ElementDAO
	{
		public function getTable()
		{
			return TABLE_PREFIX.parent::getTable();
		}

		public function getSequence()
		{
			return TABLE_PREFIX.parent::getSequence();
		}

		public function dropByElement($element)
		{
			$query =
				OSQL::delete()->
				from($this->getTable())->
				where(
					Expression::eq(
						new DBField('element_id', $this->getTable()),
						new DBValue($element->getPolymorphicId())
					)
				);

			DBPool::me()->getByDao($this)->query($query);
		}
	}
?>