<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-02-13 17:13:02                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class ElementPermissionDAO extends AutoElementPermissionDAO
	{
		public function getTable()
		{
			return TABLE_PREFIX.parent::getTable();
		}

		public function getSequence()
		{
			return TABLE_PREFIX.parent::getSequence();
		}

		public function getByGroupAndElement(Group $group, Element $element)
		{
			return
				Criteria::create($this)->
				add(
					Expression::eq(
						new DBField('group_id', $this->getTable()),
						new DBValue($group->getId())
					)
				)->
				add(
					Expression::eq(
						new DBField('element_id', $this->getTable()),
						new DBValue($element->getPolymorphicId())
					)
				)->
				setLimit(1)->
				get();
		}

		public function dropByElement(Element $element)
		{
			$query =
				OSQL::delete()->
				from($this->getTable())->
				where(
					Expression::eq(
						new DBField('element_id', $this->getTable()),
						new DBValue($element->getPolymorphicId())
					)
				);

			DBPool::me()->getByDao($this)->query($query);
		}
	}
?>