<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-02-13 17:13:02                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class ItemPermissionDAO extends AutoItemPermissionDAO
	{
		public function getTable()
		{
			return TABLE_PREFIX.parent::getTable();
		}

		public function getSequence()
		{
			return TABLE_PREFIX.parent::getSequence();
		}

		public function getListByGroup(Group $group)
		{
			return
				Criteria::create($this)->
				add(
					Expression::eqId(
						new DBField('group_id', $this->getTable()),
						$group
					)
				)->
				get();
		}

		public function getByGroupAndItem(Group $group, Item $item)
		{
			return
				Criteria::create($this)->
				add(
					Expression::eqId(
						new DBField('group_id', $this->getTable()),
						$group
					)
				)->
				add(
					Expression::eqId(
						new DBField('item_id', $this->getTable()),
						$item
					)
				)->
				setLimit(1)->
				get();
		}

		public function dropByGroup(Group $group)
		{
			$db = DBPool::me()->getByDao($this);

			$query =
				OSQL::delete()->
				from($this->getTable())->
				where(
					Expression::eqId(
						new DBField('group_id', $this->getTable()),
						$group
					)
				);

			$db->query($query);

			$this->uncacheLists();
		}
	}
?>