<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-03-31 16:27:56                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class Bind2Element extends AutoBind2Element implements Prototyped, DAOConnected
	{
		/**
		 * @return Bind2Element
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return Bind2ElementDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('Bind2ElementDAO');
		}
		
		/**
		 * @return ProtoBind2Element
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoBind2Element');
		}
		
		// your brilliant stuff goes here
	}
?>