<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-02-13 17:13:02                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class ElementPermission extends AutoElementPermission implements Prototyped, DAOConnected
	{
		/**
		 * @return ElementPermission
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ElementPermissionDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ElementPermissionDAO');
		}
		
		/**
		 * @return ProtoElementPermission
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoElementPermission');
		}
		
		// your brilliant stuff goes here
	}
?>