<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-02-06 15:27:46                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class ItemPermission extends AutoItemPermission implements Prototyped, DAOConnected
	{
		/**
		 * @return ItemPermission
		**/
		public static function create()
		{
			return new self;
		}
		
		/**
		 * @return ItemPermissionDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('ItemPermissionDAO');
		}
		
		/**
		 * @return ProtoItemPermission
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoItemPermission');
		}
		
		// your brilliant stuff goes here
	}
?>