<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-10-14 12:05:33                      *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class UserAction extends AutoUserAction implements Prototyped, DAOConnected
	{
		/**
		 * @return UserAction
		**/
		public static function create()
		{
			return new self;
		}

		/**
		 * @return UserActionDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UserActionDAO');
		}

		/**
		 * @return ProtoUserAction
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUserAction');
		}

		public function getActionTypeName()
		{
			return
				UserActionType::getActionTypeName(
					$this->getActionTypeId()
				);
		}
	}
?>