<?php
/*****************************************************************************
 *   Copyright (C) 2006-2007, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-0.10.8 at 2008-02-13 18:03:56                        *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/
/* $Id$ */

	final class User extends AutoUser implements Prototyped, DAOConnected
	{
		const LABEL = 'LTUser';

		private static $loggedUser = null;

		/**
		 * @return User
		**/
		public static function create()
		{
			return new self;
		}

		/**
		 * @return UserDAO
		**/
		public static function dao()
		{
			return Singleton::getInstance('UserDAO');
		}

		/**
		 * @return ProtoUser
		**/
		public static function proto()
		{
			return Singleton::getInstance('ProtoUser');
		}
	}
?>