<?php
/*****************************************************************************
 *   Copyright (C) 2006-2008, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1 at 2008-08-14 23:41:20                           *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoElementDAO extends StorableDAO
	{
		// no get{Table,ObjectName,Sequence} for abstract class
	}
?>