<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.0.8.99 at 2009-10-14 12:05:33                      *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/
/* $Id$ */

	abstract class AutoUserActionDAO extends StorableDAO
	{
		public function getTable()
		{
			return 'cytrus_user_action';
		}
		
		public function getObjectName()
		{
			return 'UserAction';
		}
		
		public function getSequence()
		{
			return 'cytrus_user_action_id';
		}
	}
?>